--- 
- name: Instalation mysql
  apt:
    pkg:
    - mysql-server-core-5.7.30
    - mysql-client-core-5.7.30
    - libmysqlclient-dev
    - python-mysqldb
    - mysql-server
    - mysql-client
    state: installed
    update_cache: yes

- name: Start the MySQL service
  action: service name=mysql state=started

- name: Remove the test database
  mysql_db: name=test state=absent

- name: Create user
  mysql_user: user={{mysql_user}} host="%" password={{mysql_root_password}} priv=*.*:ALL,GRANT

- name: Create new databases with names 'test' and 'itstep'
  mysql_db:
    name:
      - test
      - itstep
    state: present